import 'package:flutter/material.dart';
import 'package:termin_manager/body_builder/body_parts/templates/free_meetings_container_pattern.dart';

import './templates/free_meetings_container_pattern.dart';
import './templates/used_meetings_cont_pattern.dart';

class MeetingsPattern extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Row(
        children: [
          Column(
            children: [
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              UsedMeetingsPattern(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
            ],
          ),
          Column(
            children: [
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              UsedMeetingsPattern(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
            ],
          ),
          Column(
            children: [
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              UsedMeetingsPattern(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
            ],
          ),
          Column(
            children: [
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              UsedMeetingsPattern(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
            ],
          ),
          Column(
            children: [
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              UsedMeetingsPattern(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
              FreeMeetingsPatternContainer(),
            ],
          ),
        ],
      ),
    );
  }
}
